### ISSUE TITLE
certificate in .crt fomate 

### ISSUE THREAD

**Issue by embbo** [juangburgos/QUaServer#11]
Hi, I am using .cert string instead of byte but I have facing a problem.
UA_ByteString certificate;
	char cert[] = "-----BEGIN CERTIFICATE-----\n"
	"MIID0TCCArmDQEBCwUAMDwxFzAVBgNV\n"
	"BAMMDmp1YW5nYnVyZ29zIENBMSEwHwYDVQQKDBhqdWFuZ2J1cmdvcyBPcmdhbml6\n"
		"-----END CERTIFICATE-----\0";
	certificate.data = (UA_Byte*)cert;
	certificate.length = sizeof(cert) / sizeof(cert[0]);

In byte formate it works fine but when i used string i receive this erorr "BadEncodingLimitsExcessded"

**Comment by juangburgos** [comment]
As mentioned in [the documentation](https://github.com/juangburgos/QUaServer#server), certificates have to be in [DER format](https://wiki.openssl.org/index.php/DER). 

So you must find a way to convert your string formated certificate into DER format.

I don't know by memory how to do it, but [Google is your best friend](https://knowledge.digicert.com/solution/SO26449.html).

**Comment by juangburgos** [comment]
Closing
