### ISSUE TITLE
How to add a method and set its ID other than numeric?

### ISSUE THREAD

**Issue by eudoxos** [juangburgos/QUaServer#12]
Hi, I am now testing `addMethod` to add... a method ;) but the other side is always asking to not use numeric node IDs as they are not persistent and use string IDs instead. However, `addMethod` is returning `void` so I don't seem to have access to set those on the method node once it is created? Is there some workaround? Thanks for hints :)

**Comment by juangburgos** [comment]
If you are adding the method "manually" by using the `addMethod` method, then you might be able to set a custom nodeId by modifying `QUaBaseObject::addMethod` in [quaserver.h](https://github.com/juangburgos/QUaServer/blob/0ef4fa759863e058156ba0547354e8fc619f3b5a/src/wrapper/quaserver.h#L794) and `QUaBaseObject::addMethodNodeInternal` in [quabaseobject.cpp](https://github.com/juangburgos/QUaServer/blob/0ef4fa759863e058156ba0547354e8fc619f3b5a/src/wrapper/quabaseobject.cpp#L74), by adding an extra argument like `const QString strNodeId`.

Then use `QUaTypesConverter::nodeIdFromQString` to get a `UA_NodeId` instance and pass it as a second argument to `UA_Server_addMethodNode` [in here](https://github.com/juangburgos/QUaServer/blob/0ef4fa759863e058156ba0547354e8fc619f3b5a/src/wrapper/quabaseobject.cpp#L86).

But if you add the method as a part of a type instance (by inheriting `QUaBaseObject` and adding an *invokable* method) then is not possible at all to set a custom NodeId. 

Actually, the intended approach for OPC UA is to set custom NodeIds to *known* instances and the use **BrowsePath**s to reach an specific sub-node (i.e. a property or a method). But I can understand that there might be some limiting client implementations out there that do not support calling a method using numeric NodeIds or BrowsePaths.

If you end up modifying the `addMethod` method, send a PR. Other people might find it useful. But in that case make sure it is has a default value like `const QString strNodeId = ""` to avoid breaking the existing API. Then if the value is the default empty string, then internally use `UA_NODEID_NULL`.
