### ISSUE TITLE
Error BadCertificateHostNameInvalid 

### ISSUE THREAD

**Issue by embbo** [juangburgos/QUaServer#18]
![image](https://user-images.githubusercontent.com/35342156/70232507-e256f080-175c-11ea-82aa-ffd58c44acae.png)

Hi i am getting this error bfore i connect to server ..I am using UaExpert . Can anyone please eloborate it.

**Comment by juangburgos** [comment]
* Did you follow [these instructions](https://github.com/juangburgos/QUaServer#create-certificates) completely and correctly?

* Could you please add que UaExpoert log (appears on the bottom)?

* Could you also add the server application's log (prints to the console)?

**Comment by embbo** [comment]
1- Yes i follow all the steps

2- 

13:14:01.167 | Server Node        |  opc.tcp://l:4840              | Endpoint: 'opc.tcp://192.168.10.162:4840'
13:14:01.167 | Server Node        |  opc.tcp://l:4840              | Security policy: 'http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15'
13:14:01.167 | Server Node        |  opc.tcp://l:4840              | ApplicationUri: 'urn:unconfigured:application'
13:14:01.167 | Server Node        |  opc.tcp://l:4840              | Used UserTokenType: UserName
13:14:13.132 | AddressSpaceModel  |  opc.tcp://l:4840              | Register for ModelChangeEvents failed: createMonitoredItems returned BadNotSupported for item 0
13:14:13.134 | Server Node        |  opc.tcp://l:4840              | Connection status of server ' opc.tcp://l:4840' changed to 'Connected'.
13:14:13.135 | Server Node        |  opc.tcp://l:4840              | Revised values: SessionTimeout=1200000, SecureChannelLifetime=600000
13:14:13.139 | AddressSpaceModel  |  opc.tcp://l:4840              | Browse on node 'i=84' succeeded.
13:14:13.140 | TypeCache          |  opc.tcp://l:4840              | Reading type info of NodeId NS0|Numeric|35 succeeded
13:14:13.144 | TypeCache          |  opc.tcp://l:4840              | Reading type info of NodeId NS0|Numeric|33 succeeded
13:14:13.147 | TypeCache          |  opc.tcp://l:4840              | Reading type info of NodeId NS0|Numeric|31 succeeded
13:14:13.155 | AddressSpaceModel  |  opc.tcp://l:4840              | Browse on node 'i=85' succeeded.
13:14:13.169 | TypeCache          |  opc.tcp://l:4840              | Reading type info of NodeId NS0|Numeric|58 succeeded
13:14:13.179 | TypeCache          |  opc.tcp://l:4840              | Reading type info of NodeId NS0|Numeric|2004 succeeded

**Comment by juangburgos** [comment]
In the `exts.txt` file did you remember to add to `subjectAltName` the name that the client uses to connect to the server?

I need more information to really see what was configured incorrectly. What happens if you click the *Ignore* button? Con you still connect?

**Comment by embbo** [comment]
1. [v3_ca]
subjectAltName=DNS:localhost,DNS:ppic09,IP:127.0.0.1,IP:192.168.10.162,URI:urn:unconfigured:application
basicConstraints=CA:TRUE
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid,issuer
keyUsage=digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth,clientAuth,codeSigning

2- yes if i ignore it, it connects to server

**Comment by juangburgos** [comment]
The `ppic09` part is an example, but it must be your computer's name. You have to put *your* computer name. What troubles me from the log is the `opc.tcp://l:4840` part, is your computer's name `l`?

So if you *Ignore* then it connects, but does not print any other useful information?

**Comment by embbo** [comment]
opc.tcp://l:4840 is just name..behind is ip adress.  'opc.tcp://192.168.10.162:4840' i am using embedded device so i put ip adress also there [v3_ca]
 yes it connects without showing any problem

**Comment by embbo** [comment]
yes it connects without showing any problem

**Comment by juangburgos** [comment]
You **must** also put the computer name in `exts.txt`

**Comment by embbo** [comment]
okay let me try this... and will comeback to you

**Comment by embbo** [comment]
okay I put my computer name in it and it works fine thank you ...but i still have question why validity of certificate is 1 month ?

**Comment by juangburgos** [comment]
You can change the validity when you create it. It can be 1 month, 1 year or 100 years. Set it in the command:

```bash
# instead of : openssl req -new -x509 -days 3600 ...
openssl req -new -x509 -days 360000 ...
```

Please consider giving a github **star** to this project.
