### ISSUE TITLE
How to create arrays ?

### ISSUE THREAD

**Issue by christiangers** [juangburgos/QUaServer#25]
Hello i am trying to learn about OPC UA.
I found your wrapper classes an want to use them to create a rapid prototype of an OPC server, and i have to define 
somthing like this:
:
QUaBaseDataVariable* alarmList;	
:
	alarmList = opcLevel3->addBaseDataVariable("alarmList");
	alarmList->setDataType(QMetaType::UShort);

but my alarm list contains 15 entries so the question is how to convert this into an array ? (UShort[15])
I can not find an example in the readme ...
Kind regards
Christian

**Comment by juangburgos** [comment]
Hi, this currently works:

```c++
QUaFolderObject * objsFolder = server.objectsFolder();

auto arr = objsFolder->addBaseDataVariable("my_array");
arr->setValue(QVector<ushort>() << 1 << 2 << 3 << 4 << 5);
```

Note it is translated to OPC UA matrix type:

![image](https://user-images.githubusercontent.com/4707341/100435439-3a89af80-309e-11eb-8212-fcff8f4119bd.png)

Hope is useful,

**Comment by juangburgos** [comment]
BTW, you can also use a `QList<T>` instead of a  `QVector<T>`

**Comment by christiangers** [comment]
Thanks a lot,
![Its_done](https://user-images.githubusercontent.com/75117131/100437790-90ac2200-30a1-11eb-9211-14e2d1bbd161.png)
 so easy if you now how to do ...
