### ISSUE TITLE
Crash if an empty QStringList passed to setValue

### ISSUE THREAD

**Issue by ArsMasiuk** [juangburgos/QUaServer#40]
The library crashes after calling QUaBaseVariable::setValue(list);
if the list is empty: 

QStringList list;
QUaBaseVariable::setValue(list);

**Comment by ArsMasiuk** [comment]
Should be fixed in the Qt6 port:
https://github.com/ArsMasiuk/QUaServer-Qt6

**Comment by juangburgos** [comment]
Thanks for sharing, although it would have been better to have push request for everybody to benefit from.

**Comment by sergey-kuzminov** [comment]
Fixed a crash if an empty QStringList passed to setValue #53

**Comment by juangburgos** [comment]
Fix added by @sergey-kuzminov
